import type { Metric } from '../types/stock'

export const SECTOR_TEMPLATES: Record<string, Metric[]> = {
  Coal: [
    {
      id: 'production',
      label: 'Production Volume',
      type: 'line',
      compareType: 'bar',
      unit: 'Million Metric Tonnes',
      data: [],
    },
    {
      id: 'sales_volume',
      label: 'Sales Volume',
      type: 'line',
      compareType: 'bar',
      unit: 'Million Metric Tonnes',
      data: [],
    },
    {
      id: 'overburden_removal',
      label: 'Overburden Removal',
      type: 'bar',
      compareType: 'bar',
      unit: 'BCM',
      data: [],
    },
    {
      id: 'coal_reserve',
      label: 'Coal Reserve',
      type: 'line',
      compareType: 'bar',
      unit: 'Million Metric Tonnes',
      data: [],
    },
    {
      id: 'coal_resource',
      label: 'Coal Resource',
      type: 'line',
      compareType: 'bar',
      unit: 'Million Metric Tonnes',
      data: [],
    },
    {
      id: 'life_of_mine',
      label: 'Life of Mine (LOM)',
      type: 'line',
      compareType: 'bar',
      unit: 'years',
      data: [],
    },
  ],
  Banking: [
    {
      id: 'third_party_fund',
      label: 'Third Party Fund',
      type: 'line',
      compareType: 'bar',
      unit: 'Rp(Tn)',
      data: [],
    },
    {
      id: 'casa_ratio',
      label: 'CASA Ratio',
      type: 'area',
      unit: '%',
      dualWith: 'casa',
      data: [],
    },
    {
      id: 'casa',
      label: 'CASA',
      type: 'bar',
      unit: 'Rp(Tn)',
      data: [],
    },
    {
      id: 'time_deposit_ratio',
      label: 'Time Deposit Ratio',
      type: 'area',
      unit: '%',
      dualWith: 'time_deposit',
      data: [],
    },
    {
      id: 'time_deposit',
      label: 'Time Deposit',
      type: 'bar',
      unit: 'Rp(Tn)',
      data: [],
    },
    {
      id: 'casa_stack_deposit',
      label: 'DPK Composition',
      type: 'bar',
      unit: 'Rp(Tn)',
      stackWith: ['casa', 'time_deposit'],
      data: [],
    },
    {
      id: 'loan_growth',
      label: 'Loan YoY Growth',
      type: 'line',
      unit: '%',
      color: 'lime',
      data: [],
    },
    {
      id: 'loan',
      label: 'Loan Value',
      type: 'bar',
      unit: 'Rp(Tn)',
      color: 'orange',
      data: [],
    },
    {
      id: 'ldr',
      label: 'Loan to Deposit Ratio',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'npl',
      label: 'Non Performing Loan',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'lar',
      label: 'Loan at Risk',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'casa_growth',
      label: 'CASA Growth',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'm2',
      label: 'M2 Growth',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'nim',
      label: 'Net Interest Margin',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'roe',
      label: 'Return on Equity',
      type: 'line',
      unit: '%',
      data: [],
    },
    {
      id: 'roa',
      label: 'Return on Asset',
      type: 'line',
      unit: '%',
      data: [],
    },
  ],
}
